[package]
name = "sockjs"
version = "0.0.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "SockJS server for Actix"
readme = "README.md"
keywords = ["actor", "http", "websockets", "sockjs"]
homepage = "https://github.com/fafhrd91/actix-sockjs"
repository = "https://github.com/fafhrd91/actix-sockjs.git"
documentation = "https://fafhrd91.github.io/actix-sockjs/actix-sockjs/"
categories = ["network-programming", "asynchronous"]
license = "Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
# build = "build.rs"

[lib]
name = "sockjs"
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/main.rs"

[dependencies]
time = "0.1"
http = "0.1"
slab = "0.4"
sha1 = "0.2"
rand = "0.3"
url = "1.5"
route-recognizer = "0.1"

# serde
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

# tokio
bytes = "0.4"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"

# other
log = "0.3"
env_logger = "*"

[dependencies.actix]
version = "0.3"
# git = "https://github.com/fafhrd91/actix.git"

[dependencies.actix-web]
version = "0.1"
#path = "../actix-web"
#git = "https://github.com/fafhrd91/actix-web.git"

[profile.release]
lto = true
opt-level = 3
debug = true
